"""Domain ports (contracts) for OS-touched subsystems.

Each port is a `Protocol` (PEP 544) — duck typing structural, no inheritance
required. Adapters live in `catodo.infrastructure.{linux,macos}` and the factory
selects the right one per platform. The composition root wires them at
application startup; consumers (`mixer.py`, `mouse.py`, `channels/spotify.py`)
depend only on these protocols.

Module/contract level only — no I/O happens here, no platform-specific
imports.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MixerPort(Protocol):
    async def get_volume(self) -> int | None: ...
    async def set_volume(self, level: int) -> bool: ...
    async def set_default_sink(self, sink: str) -> bool: ...
    def is_available(self) -> bool: ...


@runtime_checkable
class InputInjectorPort(Protocol):
    async def move(self, dx: int, dy: int) -> None: ...
    async def click(self, button: int) -> None: ...
    async def scroll(self, dy: int) -> None: ...
    async def key(self, name: str, shift: bool = False) -> None: ...
    async def type_text(self, text: str) -> None: ...
    def is_available(self) -> bool: ...


@runtime_checkable
class UriOpenerPort(Protocol):
    def open(self, uri: str) -> bool: ...


@runtime_checkable
class SpotifyClientPort(Protocol):
    def is_available(self) -> bool: ...
    async def play(self) -> None: ...
    async def pause(self) -> None: ...
    async def next(self) -> None: ...
    async def previous(self) -> None: ...
    async def set_volume(self, level: float) -> None: ...
    async def open_uri(self, uri: str) -> None: ...
    async def get_state(self) -> dict[str, Any]: ...